# Práctica 08: inportar datos CSV a Python

Vamos a ver cómo importar csv cuando:
- Punto 1: datos separados por ','
- Punto 2: datos separados por ';'
- Punto 3: no hay nombres de columnas


## Punto 0:

In [1]:
# importar pandas
import pandas as pd

## Punto 1:

In [2]:
# caso1: datos separados por ',' 
pd.read_csv('datos_rrss1.csv')

      Nombre  Cantidad  ES_FBK   Año
0   Facebook      2449    True  2006
1    Twitter       339   False  2006
2  Instagram      1000    True  2010
3    YouTube      2000   False  2005
4   LinkedIn       663   False  2003
5   WhatsApp      1600    True  2009

## Punto 2:

In [8]:
# caso2: separado por ';'
pd.read_csv('datos_rrss2.csv', sep=';')

           Nombre  Cantidad  ES_FBK,Año
Facebook     2449      True        2006
Twitter       339     False        2006
Instagram    1000      True        2010

## Punto 3:

In [5]:
# caso 3 : no hay nombres de columnas
pd.read_csv('datos_rrss3.csv',
            header=None,
            names=['Nombre', 'Cantidad', 'ES_FBK', 'Año'])

      Nombre  Cantidad  ES_FBK   Año
0   Facebook      2449    True  2006
1    Twitter       339   False  2006
2  Instagram      1000    True  2010
3    YouTube      2000   False  2005
4   LinkedIn       663   False  2003
5   WhatsApp      1600    True  2009