# Data Science

## Práctica 05: PanDaS Dataframe

Cosas que se practicarán:

- Punto 1: Crear dataframes
- Punto 2: Seleccionar Elementos
- Punto 3: ordenar Columnas

# Punto 1

In [1]:
# importar pandas
import pandas as pd

In [2]:
fbk = ['Facebook', 2449, True, 2006]
twt = ['X', 339, False, 2006]
ig = ['Instagram', 1000, True, 2010]
yt = ['Youtube', 2000, False, 2005]
lkn = ['LinkedIn', 663, False, 2003]
wsp = ['WhatsApp', 1600, True, 2009]

In [3]:
lista_rrss = [fbk, twt, ig, yt, lkn, wsp]

In [4]:
# Crear Dataframe a partir de listas
df_rrss=pd.DataFrame(lista_rrss, columns=['Nombre', 'Cantidad', 'es_FBK', 'Año'])
df_rrss

      Nombre  Cantidad  es_FBK   Año
0   Facebook      2449    True  2006
1          X       339   False  2006
2  Instagram      1000    True  2010
3    Youtube      2000   False  2005
4   LinkedIn       663   False  2003
5   WhatsApp      1600    True  2009

In [5]:
# crear dataframe vacío
df_vacio = pd.DataFrame(columns=['Nombre', 'Cantidad', 'es_FBK', 'Año'])
df_vacio

Empty DataFrame
Columns: [Nombre, Cantidad, es_FBK, Año]
Index: []

In [11]:
nueva_fila = pd.DataFrame([{
    'Nombre': 'Facebook',
    'Cantidad': 2449,
    'es_FBK': True,
    'Año': 2006
}])
df_vacio = pd.concat([df_vacio, nueva_fila], ignore_index=True)
df_vacio

     Nombre Cantidad es_FBK   Año     A?o
0  Facebook     2449   True   NaN  2006.0
1  Facebook     2449   True  2006     NaN

## Punto 2

In [13]:
# Seleccionar un elemento por etiquetas
df_rrss.loc[1, 'Nombre']

'X'

In [23]:
# Seleccionaremos todo el contenido del item
df_rrss.iloc[1,0]

'X'

In [19]:
df_rrss['Nombre']

0     Facebook
1            X
2    Instagram
3      Youtube
4     LinkedIn
5     WhatsApp
Name: Nombre, dtype: str

In [20]:
df_rrss.iloc[4]

Nombre      LinkedIn
Cantidad         663
es_FBK         False
Año             2003
Name: 4, dtype: object

In [25]:
# Seleccionar por condicón Booleana
df_rrss['Cantidad']>1500

0     True
1    False
2    False
3     True
4    False
5     True
Name: Cantidad, dtype: bool

In [26]:
df_rrss[df_rrss['Cantidad']>1500]

     Nombre  Cantidad  es_FBK   Año
0  Facebook      2449    True  2006
3   Youtube      2000   False  2005
5  WhatsApp      1600    True  2009

## Punto 3

In [35]:
# Como ordenar columnas

In [36]:
# Ascendente
df_rrss.sort_values('Nombre', ascending=True)

      Nombre  Cantidad  es_FBK   Año
0   Facebook      2449    True  2006
2  Instagram      1000    True  2010
4   LinkedIn       663   False  2003
5   WhatsApp      1600    True  2009
1          X       339   False  2006
3    Youtube      2000   False  2005

In [34]:
# Descendente
df_rrss.sort_values('Cantidad', ascending=False)

      Nombre  Cantidad  es_FBK   Año
0   Facebook      2449    True  2006
3    Youtube      2000   False  2005
5   WhatsApp      1600    True  2009
2  Instagram      1000    True  2010
4   LinkedIn       663   False  2003
1          X       339   False  2006

In [ ]:
# Ordenar por dos valores

In [38]:
# Por dos columnas
df_rrss.sort_values(['Año', 'Cantidad'], ascending=[True, False])

      Nombre  Cantidad  es_FBK   Año
4   LinkedIn       663   False  2003
3    Youtube      2000   False  2005
0   Facebook      2449    True  2006
1          X       339   False  2006
5   WhatsApp      1600    True  2009
2  Instagram      1000    True  2010