# Práctica 07: importar datos de Excel a Python

Vamos a ver como importar excel cuando: 
- Punto 1: tenemos datos con nombre de columna y en la primera hoja 
- Punto 2: los datos no están en la primera hoja 
- Punto 3: no hay nombres de columnas

## Punto 0:

In [ ]:
import pandas as pd

In [ ]:
# extraer ruta del archivo
path = 'datos_rrss.xlsx'

## Punto 1:

In [6]:
# Datos completos en la primera Hoja
pd.read_excel(path)

      Nombre  Cantidad  ES_FBK   Año
0   Facebook      2449    True  2006
1    Twitter       339   False  2006
2  Instagram      1000    True  2010
3    YouTube      2000   False  2005
4   LinkedIn       663   False  2003
5   WhatsApp      1600    True  2009

## Punto 2:

In [7]:
# Caso 2, los datos no están en la primera hoja

In [9]:
pd.read_excel(path, sheet_name='Hoja2')

      Nombre  Cantidad  ES_FBK   Año
0   Facebook      2449    True  2006
1    Twitter       339   False  2006
2  Instagram      1000    True  2010

## Punto 3:

In [10]:
# no hay nombres de las columnas

In [11]:
pd.read_excel(path, sheet_name='Hoja3')

      Nombre  Cantidad  ES_FBK   Año
0   Facebook      2449    True  2006
1    Twitter       339   False  2006
2  Instagram      1000    True  2010
3    YouTube      2000   False  2005
4   LinkedIn       663   False  2003
5   WhatsApp      1600    True  2009

In [14]:
pd.read_excel(path, sheet_name='Hoja3',
              header=None,
              names=['Nombre', 'Cantidad', 'ES_FBK', 'Año'])

      Nombre  Cantidad  ES_FBK   Año
0     Nombre  Cantidad  ES_FBK   Año
1   Facebook      2449    True  2006
2    Twitter       339   False  2006
3  Instagram      1000    True  2010
4    YouTube      2000   False  2005
5   LinkedIn       663   False  2003
6   WhatsApp      1600    True  2009